# Generated by Django 4.0.4 on 2022-05-19 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('balance', models.FloatField()),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=100)),
                ('Job_desc', models.TextField()),
                ('Job_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Job_Budget', models.FloatField()),
                ('Job_Awarded', models.BooleanField()),
                ('Job_Created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_message', models.CharField(max_length=1000)),
                ('proposed_amount', models.FloatField()),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.freelancer')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Awarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job_bid')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('freelance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.freelancer')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job_detail')),
            ],
        ),
    ]
