# Generated by Django 4.0.4 on 2022-05-15 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_detail',
            name='Job_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=900),
            preserve_default=False,
        ),
    ]
