# Generated by Django 4.0.4 on 2022-05-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_job_detail_job_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='Job_desc',
            field=models.TextField(),
        ),
    ]
