# Generated by Django 4.0.4 on 2022-05-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_job_detail_job_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='Balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='Skills',
            new_name='skills',
        ),
    ]
