# Generated by Django 4.0.4 on 2022-05-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_balance_client_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_bid',
            name='client_iD',
        ),
    ]
