# Generated by Django 4.0.4 on 2022-05-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_job_bid_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_bid',
            old_name='freelancer_iD',
            new_name='freelancer_id',
        ),
    ]
